name: Keep Alive Render
on:
  schedule:
    - cron: '*/14 * * * *' # Gira ogni 14 minuti
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -I https://rgandja-api.onrender.com
